general {
    col.active_border = rgba({{colors.primary.default.hex_stripped}}ff)
    col.inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}aa)
}

misc {
    background_color = rgba({{colors.surface.default.hex_stripped}}ee)
}
