foreground            #f0dede
background            #1a1111
selection_foreground  #ffdad9
selection_background  #5d3f3f
url_color             #ffb3b3
cursor                #f0dede
cursor_text_color     #1a1111

# Tabs
active_tab_foreground   #ffdad9
active_tab_background   #733335
inactive_tab_foreground #d7c1c1
inactive_tab_background #524343

# The 16 terminal colors
# black
color0 #1a1111
color8 #524343
# red
color1 #ffb4ab
color9 #ffb4ab
# green
color2 #a6e3a1
color10 #a6e3a1
# yellow
color3 #f9e2af
color11 #f9e2af
# blue
color4 #ffb3b3
color12 #ffb3b3
# magenta
color5 #e6bdbc
color13 #e6bdbc
# cyan
color6 #e5c18d
color14 #e5c18d
# white
color7 #d7c1c1
color15 #f0dede
