foreground            #ebe1d4
background            #17130b
selection_foreground  #f5e0bb
selection_background  #52452a
url_color             #e9c16c
cursor                #ebe1d4
cursor_text_color     #17130b

# Tabs
active_tab_foreground   #ffdf9e
active_tab_background   #5b4300
inactive_tab_foreground #d0c5b4
inactive_tab_background #4d4639

# The 16 terminal colors
# black
color0 #17130b
color8 #4d4639
# red
color1 #ffb4ab
color9 #ffb4ab
# green
color2 #a6e3a1
color10 #a6e3a1
# yellow
color3 #f9e2af
color11 #f9e2af
# blue
color4 #e9c16c
color12 #e9c16c
# magenta
color5 #d8c4a0
color13 #d8c4a0
# cyan
color6 #b0cfa9
color14 #b0cfa9
# white
color7 #d0c5b4
color15 #ebe1d4
