# Display menu (very modern look)
menu        script-binding uosc/menu
mbtn_right  script-binding uosc/menu
s           script-binding uosc/subtitles          # Manage subs
a           script-binding uosc/audio              # Manage audio tracks
q           script-binding uosc/stream-quality     # Quality for YT/Streams
p           script-binding uosc/items              # Playlist/Files
o           script-binding uosc/open-file          # Open file picker

# Seeking
RIGHT       seek  5
LEFT        seek -5
UP          add volume  2
DOWN        add volume -2

# Video quality profiles
ctrl+1      change-list glsl-shaders set "~~/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl"
ctrl+0      change-list glsl-shaders clr ""
