# Essential to enable global keybinds and catchall behavior
exec = hyprctl dispatch submap global
submap = global

# ======= Core (default Hyprland config structure) =======
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/execs.conf
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/colors.conf
source = ~/.config/hypr/hyprland/keybinds.conf

# ======= Custom (your overrides / safe edits) =======
source = ~/.config/hypr/custom/env.conf
source = ~/.config/hypr/custom/execs.conf
source = ~/.config/hypr/custom/general.conf
source = ~/.config/hypr/custom/rules.conf
source = ~/.config/hypr/custom/keybinds.conf

# ======= Temporary Autostart (Self-destructs after completion) =======
# source = ~/.config/hypr/autostart_once.conf
