general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

# Lock after 5 min of inactivity
listener {
    timeout = 1000
    on-timeout = $HOME/.config/hyprlock/scripts/hyprlock.sh
}

listener {
    timeout = 6600
    on-timeout = notify-send "⚠️ Auto Shutdown" "System will power off in 5 minutes (locked for 1h)."
    only-when-locked = true
}

listener {
    timeout = 6700
    on-timeout = systemctl poweroff
    only-when-locked = true
}
