general {
    col.active_border   = rgba(DF5B14AA)
    col.inactive_border = rgba(000000AA)
}
misc {
    # fallback safely to color0
    background_color = rgba(000000EE)
}
#windowrulev2 = bordercolor rgba(E7BFAAAA) rgba(A1867777),pinned:1
